### ISSUE TITLE
解压密码无效

### ISSUE THREAD

**Issue by L-Jovi** [catofmrlu/MacApps#13]
楼主我下载的迅雷 dmg 解压的时候输入你 readme 提供的提取码无效，是更换过压缩密码了嘛~

**Comment by catofmrlu** [comment]
> 楼主我下载的迅雷 dmg 解压的时候输入你 readme 提供的提取码无效，是更换过压缩密码了嘛~
这两个都试了么？
maccrack.cn 或 xclient.info

**Comment by catofmrlu** [comment]
这两个都试了么？
maccrack.cn 或 xclient.info

**Comment by L-Jovi** [comment]
感谢 LZ~
