### ISSUE TITLE
应用的链接已经被吞惹~

### ISSUE THREAD

**Issue by lowingly** [catofmrlu/MacApps#19]
如题(′д｀)

**Comment by catofmrlu** [comment]
你好

由于百度云限制，请加百度云：福布斯时刻

我会及时分享给你

发自我的 iPhone

在 2019年6月23日，11:09，WingLo <notifications@github.com<mailto:notifications@github.com>> 写道：


如题(′д｀)

**Comment by lowingly** [comment]
谢谢 知道啦~
