### ISSUE TITLE
更新频率提升告知

### ISSUE THREAD

**Issue by catofmrlu** [catofmrlu/MacApps#4]

**Comment by thu-zxs** [comment]
游戏链接失效了～

**Comment by lxxlxx888** [comment]
你好

由于百度吞链接太厉害，链接经常失效，请见谅！！

这是游戏链接：https://pan.baidu.com/s/1geNyL7H
请速保存！！随时失效！！

-------------
鲁新新

**Comment by thu-zxs** [comment]
谢谢🙏

**Comment by k354250377** [comment]
又失效了

**Comment by lxxlxx888** [comment]
链接：https://pan.baidu.com/s/1EpqYjQCjFh2SQGa79Qu7Aw 密码：f888

如失效，请告知
